import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const aeonik = localFont({
  src: [
    {
      path: "./fonts/fonnts.com-Aeonik-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/fonnts.com-Aeonik-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-aeonik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${aeonik.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
